### PR TITLE
Create icon.png

### PR DESCRIPTION
**Pull request by ColdIce1605**
Please the Modmenu

### CODE REVIEW

**Comment by haykam821** [comment]
This doesn't seem to have an actual icon. Is there a warning that is being suppressed by this?

**Comment by ColdIce1605** [comment]
yes just wait

**Review by haykam821 — CHANGES_REQUESTED** [review]
`[The `icon` field in `fabric.mod.json`](https://github.com/NucleoidMC/anonymize/blob/493e5b0252d6be423152fe963772ed0b2562273b/src/main/resources/fabric.mod.json) indicates the logo should be at `assets/anonymize/icon.png`, but this pull request places the icon at `anonmize/icon.png`.

**Comment by ColdIce1605** [comment]
yes I know, im doing this all on github

**Comment by ColdIce1605** [comment]
ok everything is fixed 👍

**Review by haykam821 — CHANGES_REQUESTED** [review]
The icon is currently at `anonymize/icon.png`, rather than `assets/anonymize/icon.png`.

**Comment by ColdIce1605** [comment]
well im never doing this again

**Pull request closed without merging**
